--- #YAML:1.0
name:                Ham-Reference-Phonetics
version:             0.02
abstract:            A quick reference for the ITU Phonetic Alphabet.
license:             artistic2
author:              
    - Brad McConahay N8QQ <brad@n8qq.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
